FROM  node:14
LABEL maintainer="Manish Prakash<manish@excellencetechnologies.in"

WORKDIR /workspace

VOLUME [ "/workspace/src" ]
# COPY src /workspace/src

COPY package.json /workspace/package.json
COPY karma.conf.js /workspace
COPY angular.json /workspace/angular.json
COPY tslint.json /workspace.tslint.json
COPY tsconfig.app.json /workspace
COPY tsconfig.json /workspace/tsconfig.json
COPY tsconfig.spec.json /workspace
COPY tslint.json /workspace
COPY browserslist /workspace/browserslist

RUN npm install -g @angular/cli

RUN npm install


CMD [ "ng" , "serve" , "--host", "0.0.0.0"]